// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuKgDCsf2x3-MZluxznuFEdpmiDeTYaF0',
    appId: '1:688745203053:web:0d137af015048292c14664',
    messagingSenderId: '688745203053',
    projectId: 'pointage-a04c7',
    authDomain: 'pointage-a04c7.firebaseapp.com',
    storageBucket: 'pointage-a04c7.appspot.com',
    measurementId: 'G-9VREJKQ6VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOa8erIJWpFKNJ8aC9g7N8wn6CDxFf-z4',
    appId: '1:688745203053:android:583a80aa600eccaec14664',
    messagingSenderId: '688745203053',
    projectId: 'pointage-a04c7',
    storageBucket: 'pointage-a04c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB35Syybz2tTsgyydQa7zaTjJgtYqe14hQ',
    appId: '1:688745203053:ios:b0fa60397bdb5942c14664',
    messagingSenderId: '688745203053',
    projectId: 'pointage-a04c7',
    storageBucket: 'pointage-a04c7.appspot.com',
    iosBundleId: 'com.example.pointage',
  );
}
